spring.application.name=automatizador
# Importar archivo .env si existe (forma nativa y segura para producción)
spring.config.import=optional:file:.env[.properties]
# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cobranza_proyeccion?createDatabaseIfNotExist=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Logging para ver qué hace el bot
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.proyeccion.cobranza=INFO
logging.level.org.springframework.web.reactive.function.client.WebClient=DEBUG

# Credenciales API Siigo
siigo.api.url=${SIIGO_API_URL:https://api.siigo.com/v1}
siigo.username=${SIIGO_USERNAME}
siigo.access_key=${SIIGO_ACCESS_KEY}


# Credenciales# Microsoft Graph (Daemon/Unattended Access)
microsoft.graph.tenant-id=${MICROSOFT_GRAPH_TENANT_ID:}
microsoft.graph.client-id=${MICROSOFT_GRAPH_CLIENT_ID:}
microsoft.graph.client-secret=${MICROSOFT_GRAPH_CLIENT_SECRET:}
microsoft.graph.drive-id=${MICROSOFT_GRAPH_DRIVE_ID:}
microsoft.graph.excel-item-id=${MICROSOFT_GRAPH_EXCEL_ITEM_ID}