spring.application.name=automatizador
# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cobranza_proyeccion?createDatabaseIfNotExist=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Logging para ver qué hace el bot
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.proyeccion.cobranza=INFO